name: Neon Keep-Alive

on:
  schedule:
    - cron: '*/4 * * * *'  # a cada 4 minutos
  workflow_dispatch:        # permite rodar manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Neon
        run: psql "${{ secrets.DATABASE_URL }}" -c "SELECT 1;" -q
